server:
  servlet:
    encoding:
      charset: utf-8
      enabled: true

logging:
  level:
    "[org.hibernate.type]": trace

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create #create, update, none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true #쿼리를 화면에 뿌려준다.

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: --
            client-secret: --
            scope:
              - email
              - profile

          naver:
            client-id: --
            client-secret: --
            scope:
              - email
              - profile
            client-name: Naver
            authorization-grant-type: authorization_code #네이버는 code 를 받아서 token 처리하는 로그인을 한다. 이거철자틀리면 에러남
            redirect-uri: -- #구글,페이스북은 이게 기본값이라 안적어줘도 되는데 네이버는 바꿀수 있어서 적어줘야 한다.

        #구글,페이스북은 아래 내용이 자기네 사이트 내부에서 설정해 놔서 안해두 되지만 네이버는 해줘야 한다.
        #설정된 내용은 비슷하니까. 로그인되는 패턴은 동일하다고 생각하면 된다.
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize #네이버문서>개발가이드에 이주소로 요청시 네이버로그인창이 뜬다고 되어 있다.
            token-uri: https://nid.naver.com/oauth2.0/token #토큰발급 신청하는 주소이다.
            user-info-uri: https://openapi.naver.com/v1/nid/me #토큰을 가지고 사용자프로필API 를 요청한다.
            user-name-attribute: response #회원정보를 json으로 받는데 response 라는 키값으로 네이버가 리턴해준다.
